name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            rid: linux-x64
          - os: windows-latest
            rid: win-x64
          - os: macos-latest
            rid: osx-x64
    
    runs-on: ${{ matrix.os }}
    env:
      CI: true
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Create Secrets.cs file
        run: |
          cat > DiffKeep/Settings/Secrets.cs << 'EOL'
          namespace DiffKeep.Settings;

          public static class Secrets
          {
              public const string FeedbackApiKey = "${{ secrets.FEEDBACK_API_KEY }}";
          }
          EOL
        shell: bash

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Publish
        run: dotnet publish DiffKeep/DiffKeep.csproj -c Release -r ${{ matrix.rid }} --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true -o publish/${{ matrix.rid }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: diffkeep-${{ matrix.rid }}
          path: publish/${{ matrix.rid }}
          retention-days: 7

  create-release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create release zip files
        run: |
          for dir in diffkeep-*/; do
            zip -r "${dir%/}.zip" "$dir"
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: diffkeep-*.zip
          generate_release_notes: true